services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432

  photographer:
    depends_on:
      - postgres
    container_name: photographer
    volumes:
      - service-logs:/home/gradle/source/logs
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      CERT_KEY_PATH: ${CERT_KEY_PATH}
      CERT_PATH: ${CERT_PATH}
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080

volumes:
  db-data:
    driver: local
  service-logs:
    driver_opts:
      type: none
      device: /home/logs
      o: bind