services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
#    volumes:
#      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432

  photographer:
    depends_on:
      - postgres
    container_name: photographer
#    volumes:
#      - service-logs:/home/gradle/source/logs
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      KEY_STORE_PATH: ${KEY_STORE_PATH}
      KEY_STORE_PASSWORD: ${KEY_STORE_PASSWORD}
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080

#volumes:
#  db-data:
#    driver: local
#    driver_opts:
#      type: none
#      device: ~/db_data
#      o: bind
#  service-logs:
#    driver: local
#    driver_opts:
#      type: none
#      device: ~/logs
#      o: bind