server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store-password: password
    key-store: file:./keystore/keystore.p12
    key-alias: tomcat

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}