server:
  ssl:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}



photographers:
  employee:
    default-email: aaa@aaa.com
    default-password: 1234