debug: true

spring:
  application:
    name: photographer

  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
      maximum-pool-size: 2
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:db/changelog/changelog.xml

springdoc:
  api-docs:
    enabled: true
