server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store: ${KEY_STORE_PATH}
    key-alias: tomcat
  servlet:
    session:
      timeout: 120m

spring:
  application:
    name: photographer

  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
      maximum-pool-size: 2
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:db/changelog/changelog.xml

  session:
    store-type: jdbc

springdoc:
  api-docs:
    enabled: true

logging:
  file:
    name: ./logs/photographer.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd-HH}.%i.log
      max-file-size: 500KB # by size
      max-history: 24
  level:
    sql: debug
    root: info
    web: debug

default:
  advice:
    debug: true

photographers:
  jobs:
    notify: "5 4 * * * *"
  default-image: classpath:/static/default.jpg
  mediaTypes:
    - image/jpeg
    - image/jpg
